### ISSUE TITLE
请问性能测试和具体测试程序和测试场景是什么？

### ISSUE THREAD

**Issue by zhongchengyong** [Gallium70/rv-n-ext-impl#1]
学习你们对N扩展的研究中，并且有对性能做评估：https://gallium70.github.io/rv-n-ext-impl/ch4_1_uei_analysis.html  
请问你们使用的测试程序在哪可以找到吗？具体测试过程是什么？以及N扩展带来的性能收益，你们分析原因是什么？（我粗浅的理解，实现与否在处理中断时需要save/restore的上下文信息是类似的，N扩展维护了M mode和S mode类似的CSR和指令）

**Comment by Gallium70** [comment]
裸机环境的测试程序：[rv-csr-test](https://github.com/duskmoon314/rv-csr-test/blob/multicore-serial/src/main.rs)
rCore-N里的测试程序：[uart_benchmark.rs](https://github.com/duskmoon314/rCore-N/blob/master/user/src/bin/uart_benchmark.rs) 和 [uart_load.rs](https://github.com/duskmoon314/rCore-N/blob/master/user/src/bin/uart_load.rs) ，进shell之后直接调uart_benchmark就行。

吞吐量的数据直接在测试程序里就有输出，而每次操作的时长统计是靠插了一堆trace来做的：[trace mod](https://github.com/duskmoon314/rCore-N/blob/master/os/src/trace/mod.rs) ，大概思路就是读一下cpu cycle寄存器，然后写到系统不会用到的内存区域里，再从外界读出去。目前这个只在zcu102的fpga板上实现了，整个rCore-N用16M，而物理上有2G的内存，rv这边写进去之后从arm核那边读。读出来之后用 [analyze-trace.py](https://github.com/duskmoon314/rCore-N/blob/master/trace/analyze-trace.py) 这个脚本做统计。

性能收益目前推测主要是省在了跳过系统调用的接口上，不用ecall也不用换页表了，trap上下文直接压在了用户栈上，这样整个局域性都会好很多；更精细的分析目前还在进行中。

**Comment by zhongchengyong** [comment]
好的，感谢答疑。期待进一步的分析结果
